### ISSUE TITLE
Updating deleted event config ID

### ISSUE THREAD

**Issue by strangechange0** [gessnerfl/terraform-provider-instana#140]
Terraform performs an `update` on a non-existent event configuration ID. A potential recovery behavior here could be that it will create another event configuration if the original event does not exist (due to accidental deletion or something else) 

> [1m[31mError: [0m[0m[1mfailed to send HTTP PUT request to Instana API; status code = 400; status message = 400 Bad Request; Headers map[Cache-Control:[no-store, max-age=0] Content-Length:[128] Content-Type:[application/json;charset=utf-8] Date:[Tue, 20 Sep 2022 17:29:20 GMT] Referrer-Policy:[same-origin] Server:[openresty] Server-Timing:[intid;desc=2519873789937ee7] Vary:[Cookie, Authorization] X-Content-Type-Options:[nosniff] X-Frame-Options:[deny] X-Permitted-Cross-Domain-Policies:[none] X-Ratelimit-Limit:[10000] X-Ratelimit-Remaining:[9697] X-Ratelimit-Reset:[1663696448] X-Ratelimit-Zone:[39m X-Xss-Protection:[1; mode=block]]
Body: {"errors":["The \"UPDATE\" operation failed because the event configuration with ID c9a6fuc42ebd7l169r80 was already deleted."]}[0m

**Comment by gessnerfl** [comment]
@strangechange0: my understanding here is, that by accident you deleted a resource which was managed by your terraform code from the Instana UI or via Instana API. Is this assumption correct?

If this is the case the behaviour is valid. It is not the job of the provider to guess what could be the right behaviour. In case a resource was deleted by accident you would have to remove it as well from the TF state so that it gets created.
